### ISSUE TITLE
issue in adding patient data through /addpatients

### ISSUE THREAD

**Issue by Ameya-121** [neshvig10/DBMS-Project_Snigdha-Hospitals#4]
Although data is being entered and submitted via _/addpatients_, it is not reflecting in the database. 
A new entry is created in the **patient** table with all null values.

Interestingly, the id is being entered in the portal, in **patient** table shows values based on auto indexing

**Comment by neshvig10** [comment]
Fixed it by changing variables 
Pushed changes to main
